Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,s: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite 1 numeo")
 leia (a)
 s <- (a*25)/100
 escreva("25% de ",a, "è", s)

Fimalgoritmo