Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,b,s: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite 2 numeo")
 leia (a,b)
 s <- (a+b)*45/100
 escreva("45% da soma de ",a ,"mais",b ,"è", s)

Fimalgoritmo