Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
Z,A,L,C: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva("digite 3 numeo")
 leia (L,A,C)
 Z <- (L+A)*2/C
 escreva("O valor para a formula aplicada é ",Z)

Fimalgoritmo